Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/FrozenStringLiteralComment:
  Enabled: false

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'test/**/*'