Style/Alias:
  EnforcedStyle: prefer_alias_method

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ReturnNil:
  Enabled: true

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/Lambda:
  Enabled: false

Style/RedundantRegexpEscape:
  Enabled: false

Style/MixedRegexpCaptureTypes:
  Enabled: false

Style/KeywordParametersOrder:
  Enabled: false

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Naming/UncommunicativeMethodParamName:
  AllowedNames:
    - x
    - y
    - ph
    - pw
    - ip
    - id
