require: rubocop-rails
inherit_from:
  - .rubocop-ruby.yml

Metrics/BlockLength:
  Exclude:
    - 'app/views/**/*.xml.builder'

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'test/**/*'
    - 'spec/**/*'
    - 'Rakefile'
