require: rubocop-rails
inherit_from:
  - .rubocop-ruby.yml

Metrics/BlockLength:
  Exclude:
    - 'app/views/**/*.xml.builder'

Rails/SkipsModelValidations:
  Whitelist:
    - touch

AllCops:
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/**/*'
    - 'node_modules/**/*'
    - 'test/**/*'
    - 'Rakefile'
